name: Deploy Worker

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/worker.js'
      - 'wrangler.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker
    steps:
      - uses: actions/checkout@v3
      
      # 使用 Cloudflare 官方 GitHub Action
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # 如果你的 wrangler.toml 不在根目录，可以指定路径
          # configPath: wrangler.toml
