name: Deploy Worker

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install wrangler
      
      - name: Deploy Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          echo "开始部署 Worker..."
          echo "使用账户 ID: $CLOUDFLARE_ACCOUNT_ID"
          echo "API 令牌已设置: ${{ secrets.CLOUDFLARE_API_KEY != '' }}"
          
          echo "wrangler.toml 内容:"
          cat wrangler.toml
          
          npx wrangler deploy
